name: Prevent Direct Merges into Minor

on:
  pull_request:
    branches:
      - minor

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check source and target branches
      run: |
        if [[ "${{ github.event.pull_request.base.ref }}" == "minor" && ! "${{ github.event.pull_request.head.ref }}" =~ ^feature/ ]]; then
          echo "Pull requests to minor can only be merged from feature/* branches."
          exit 1
        else
          echo "This pull request is allowed."
        fi
