name: Prevent Direct Merges into Master

on:
  pull_request:
    branches:
      - master

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check source and target branches
      run: |
        if [[ "${{ github.event.pull_request.base.ref }}" == "master" && "${{ github.event.pull_request.head.ref }}" != "minor" ]]; then
          echo "Pull requests to master can only be merged from minor branch."
          exit 1
        else
          echo "This pull request is allowed."
        fi
