name: Publish Minor Version

on:
  pull_request:
    types: [closed]
    branches:
      - minor

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Bump minor version
      run: pwsh ./.github/scripts/VersionBump.ps1 -Mode minor

    - name: Commit bumped version
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add Directory.Build.props
        git commit -m "Bump minor version"
        git push

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack
      run: dotnet pack --configuration Release --no-build

    - name: Push Mappah
      run: dotnet nuget push src/Mappah/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

    - name: Push Mappah.Extensions
      run: dotnet nuget push src/Mappah.Extensions/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
